Proyecto-Front Best Music Pe
JordanEsquivelS/BusquedaCancion-Frontend pull request #1
Opened 2023-10-25 20:40 UTC by JordanEsquivelS

Solo será proyecto Front-end usando la api Spotify a través de RapidAPI, se dejó las claves para la revisión, luego se incluirán en el  archivo .env

2023-10-27 10:46 UTC, Educg550 requested changes
# **¡Hola Jordan!** 😃🙋‍♂️


¡Gracias por enviar tu proyecto para revisión! Sin embargo, parece que la funcionalidad de busca no funciona adecuadamente, y debe ser solucionada hasta la próxima iteración. Échale un vistazo a las demarcaciones hechas en tu proyecto devuelto para mejores detalles en el error causado. Esta no contará como una revisión y, por lo tanto, aún tienes 4 intentos más.

*Un pequeño recordatorio*:

Ten en cuenta que tu proyecto será corregido por completo cuando todas las observaciones marcadas como "Necesita corrección" sean solucionadas. Por eso, nota que aún puede haber más problemas que los destacados en esta devolución dentro de tu proyecto. ¡Éxito y buena suerte en tus estudios!

2023-10-27 10:46 UTC, Educg550 commented on src/utils/api.js
> +    console.error(
Parece que se causa un error en tu requisicion con `fetch`: 

- https://i.imgur.com/nmhpaMe.png

Prueba verificar las configuraciones del token que estás enviando para el servidor de la API y si está actualizado como debería

2023-10-27 13:57 UTC, JordanEsquivelS commented
Hola Eduardo, buenos días, escribí al dueño del api, hubo una actualización y me dijo que era un error interno y que iba a ser arreglado, adjunto evidencia, estaba esperando si hubiera  otra actualización, pero ya esta funcionando la api otra vez, podrías seguir revisando mi código, gracias, 
![Pregunta_Servidor](https://github.com/JordanEsquivelS/BusquedaCancion-Frontend/assets/121452437/1707f806-1642-4601-8ebd-9d9705b310fe) 
![Demo](https://github.com/JordanEsquivelS/BusquedaCancion-Frontend/assets/121452437/75ccc9de-4027-4909-8f4c-b9123ea13623)

2023-10-27 14:09 UTC, JordanEsquivelS commented
Hola Eduardo, buenos días, escribí al dueño del api, hubo una actualización y me dijo que era un error interno y que iba a ser arreglado, adjunto evidencia, estaba esperando si hubiera otra actualización, pero ya esta funcionando la api otra vez, podrías seguir revisando mi código, gracias. 
![Pregunta a dueño](https://github.com/JordanEsquivelS/BusquedaCancion-Frontend/assets/121452437/19d9606d-9572-46e5-8e1f-292eb5e36313)

2023-10-29 13:48 UTC, Educg550 approved these changes
# **¡Hola Jordan!** 😃🙋‍♂️

Me gustó mucho la creatividad de tu proyecto, creaste una página de búsqueda responsiva y muy hermosa usando todos tus conocimientos de Front-end, usaste una linda paleta de colores y identidad visual minimalista para decorar tu página con una excelente combinación, ¡muy bien hecho! Además, ahora sí se hacen las llamadas a API correctamente, comprobé que en el momento de la última corrección había pasado un error interno en la API, y no en tu proyecto. Aquí están sus puntos:

**Marcado y JSX**: 72.74 (hay hooks llamados afuera de componentes principales de tu aplicación, podrías haber usado más `then` en tus requisiciones async)

**Buenas prácticas**: 15 (puntuación perfecta en ese tópico!)

**Recomendaciones**: 5 (puntuación perfecta en ese tópico!)

**PUNTUACIÓN TOTAL: 92.74** (¡Aprobado, felicitaciones!) Has demostrado buenas prácticas en su código y buenos hábitos de estandarización en su desarrollo, y mostraste habilidad con el estilo y el funcionamiento de su página, está bien diseñada y sigue la metodología BEM, en su mayor parte, ¡Felicidades! ¡Te deseo éxito en tu carrera como desarrollador!

2023-10-29 13:48 UTC, Educg550 commented on src/hooks/useOutsideAlerter.js
> +  useEffect(() => {
Busca usar `hooks` solamente en componentes principales de tu aplicación

2023-10-29 13:48 UTC, Educg550 commented on src/utils/api.js
> +    const response = await fetch(url, options);
Tu código puede ser mejorado haciendo `then` chaining en lugar de usar varios bloques `try - catch`

2023-10-30 15:09 UTC, merged